# version: 1.0.0
add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[](bold italic cyan)"
error_symbol = "[](italic red)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[hostname]
ssh_only = false
style = "bright-yellow bold italic"
format = "[ $hostname]($style)"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[ ⭘ $user]($style) "
disabled = false
show_always = true

[directory]
home_symbol = " ~"
truncation_length = 2
truncation_symbol = " "
read_only = " ◈"
use_os_path_sep = true
style = "italic purple"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold purple'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [](bold bright-blue)'

[cmd_duration]
format = "[◄ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[](bold italic bright-blue)"
style = "italic bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = []
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = true

[git_status]
style = "bold italic bright-blue"
format = "([ $ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed ]($style))"
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◃◈](italic white)"
modified = "[●◦](italic yellow)"
staged = "[▪┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

[lua]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "󰢱 "
style = "bold bright-red"

[nodejs]
format = "[ ($version)](bold red)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [${symbol}${version}]($style)"
symbol = "[](bold red) "
version_format = "${raw}"
style = "bold bright-red"

[ruby]
format = " [${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold bright-red"

[rust]
format = " [$symbol$version]($style)"
symbol = " "
version_format = "${raw}"
style = "bold bright-red"

[package]
format = "[$symbol$version]($style)"
version_format = "${raw}"
symbol = " "
style = "dimmed yellow italic bold"

[swift]
format = " [${symbol}${version}]($style)"
symbol = "󰛥 "
style = "bold bright-red"
version_format = "${raw}"

[aws]
disabled = false
format = " [$symbol $profile $region]($style)"
style = "bold bright-red"
symbol = " "

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"
style = "bold bright-red"

[cpp]
symbol = " "
format = " [$symbol($version(-$name))]($style)"
style = "bold bright-red"

[conda]
symbol = " "
format = " [$symbol$environment]($style)"
style = "bold bright-red"

[docker_context]
symbol = " "
format = " [$symbol$context]($style)"
style = "bold bright-red"

[golang]
symbol = " "
format = " [$symbol($version )]($style)"
style = "bold bright-red"

[java]
symbol = " "
format = " [${symbol}(${version} )]($style)"
style = "bold bright-red"
