theme = "base16_transparent"

[editor]
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "hidden"

# Keybindings for insert mode
[keys.insert]
"A-h" = "move_char_left"
"A-j" = "move_line_down"
"A-k" = "move_line_up"
"A-l" = "move_char_right"

up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
