theme = "base16_transparent"

[editor]
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "hidden"
soft-wrap.enable = true

[keys.insert]
"A-h" = "move_char_left"
"A-j" = "move_line_down"
"A-k" = "move_line_up"
"A-l" = "move_char_right"
"S-A-l" = "goto_line_end"
"S-A-h" = "goto_line_start"
